### ISSUE TITLE
Unable to find connectorx version on linux/aarch64

### ISSUE THREAD

**Issue by MatsMoll** [sfu-db/connector-x#535]
#### What language are you using?

**Python**

#### What version are you using?

Trying to install 0.3.2

#### Can you describe your bug?

When installing connectorx on a `linux/aarch64` (docker on an M2 Mac) architecture, `pip` not be able to find any versions to install.

#### What are the steps to reproduce the behavior?

I have a Docker image built similar to the following.

```Dockerfile
FROM python:3.10.5-slim
RUN pip install connectorx==0.3.2
```

If this is build on an M2 Mac will it fail.

#### What is the error?

The error is the following:

```
67.29   RuntimeError
67.29
67.29   Unable to find installation candidates for connectorx (0.3.2)
67.29
67.29   at /usr/local/lib/python3.10/site-packages/poetry/installation/chooser.py:73 in choose_for
67.29        69│
67.29        70│             links.append(link)
67.29        71│
67.29        72│         if not links:
67.29     →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
67.29        74│
67.29        75│         # Get the best link
67.29        76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
67.29        77│
```

#### Why it fails
When running `pip index versions connectorx` in an interactive docker image on a `linux/aarch64` platform, will the following be returned.

```bash
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
connectorx (0.2.3)
Available versions: 0.2.3
```

The only difference between `0.2.3` and later versions is that it contains a source distribution.
Ideally something like a dedicated `linux/aarch64` image could have been built, but providing a source distribution would also be nice.

#### Potential fix?
Looking at the CI for the `0.2.3` version do I see that an extra step is added.

```
- name: Persist artifacts source code
        uses: actions/upload-artifact@v2
        if: matrix.python-version == 39
        with:
          name: "linux-${{ matrix.python-version }}"
          path: connectorx-python/dist/*.tar.gz
```
However, this have been removed in later versions, which makes me assume that this was not working totally as expected?
