### ISSUE TITLE
Dev: Create a rust `rust-toolchain.toml` file to store the toolchain version

### ISSUE THREAD

**Issue by DeflateAwning** [sfu-db/connector-x#791]
Here's an example of what it looks like for Polars:

```toml
[toolchain]
channel = "nightly-2025-03-07"
```

Would streamline the dev setup guide, which currrently suggests searching for the version in a GitHub Actions file
